"""
SttAdapter — termux-stt (whisper.cpp / sherpa-onnx) Vulkan Acceleration Adapter
Zero-Silent-Fallback and Anti-Deception Compliant Engine Orchestrator
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import struct
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..exceptions import AmevaRuntimeError, PlatformNotSupportedError
from ..protocol import BindingResult
from .base import (
    _is_vulkan_report,
    _make_cpu_binding,
    resolve_diagnostic_report,
    get_vulkan_env,
    BaseAdapter,
    check_vulkan_availability_or_raise,
)

logger = logging.getLogger("ameva_runtime.adapters.stt")

_MISSING = object()
_ACTIVE_SNAPSHOTS: Dict[int, Dict[str, Any]] = {}

CPU_FALLBACK_PATTERNS = (
    "no gpu found",
    "using cpu backend",
    "falling back to cpu",
    "fallback to cpu",
    "vulkan initialization failed",
    "failed to initialize vulkan",
    "no vulkan device",
    "backend unavailable",
    "ggml_vulkan: failed",
)

VULKAN_INIT_PATTERNS = (
    "ggml_vulkan: using device",
    "ggml_vulkan: found 1 vulkan device",
)


def _calculate_whisper_layers(engine: Any = None) -> int:
    """Calculates GPU offload layers for Whisper models."""
    if engine is not None:
        if hasattr(engine, "gpu_layers") and getattr(engine, "gpu_layers", 0) > 0:
            return int(engine.gpu_layers)
        if hasattr(engine, "config") and hasattr(engine.config, "gpu_layers") and engine.config.gpu_layers > 0:
            return int(engine.config.gpu_layers)
    return 32


def _calc_file_sha256(path: Path) -> str:
    """Computes SHA-256 hex digest of a file in 1MB chunks."""
    digest = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().lower()


def has_vulkan_link_hint(path: Any) -> bool:
    """Static Heuristic Pre-filter (Notice: NOT a conclusive capability verification).
    Verifies that the file is a 64-bit ARM64 ELF binary and contains string hints of
    Vulkan compute libraries (libvulkan.so or libggml-vulkan).
    """
    p = Path(path).expanduser().resolve(strict=False)
    if not p.is_file():
        return False
    try:
        with open(p, "rb") as f:
            header = f.read(64)
            if len(header) < 20 or not header.startswith(b"\x7fELF"):
                return False
            is_64 = header[4] == 2
            is_little = header[5] == 1
            machine = int.from_bytes(header[18:20], "little" if is_little else "big")
            # 183 is AArch64
            if not (is_64 and is_little and machine == 183):
                return False
            content = header + f.read(8 * 1024 * 1024)
            return (b"libvulkan.so" in content) or (b"libggml-vulkan" in content)
    except Exception as exc:
        logger.warning("[ameva-runtime:SttAdapter] has_vulkan_link_hint failed on %s: %s", p, exc)
        return False


def verify_stt_manifest(
    binary_path: Path,
    manifest_path: Optional[Path] = None,
) -> Dict[str, Any]:
    """Verifies that the binary and its dependent runtime libraries match the cryptographic manifest
    generated by NativeAssetManager.
    """
    home = Path(os.environ.get("HOME", os.path.expanduser("~")))
    prefix = Path(os.environ.get("PREFIX", "/data/data/com.termux/files/usr"))
    prefix_manifest = prefix / "share" / "ameva" / "manifests" / "stt.json"
    default_manifest = home / ".local" / "share" / "ameva" / "manifests" / "stt.json"
    release_manifest = home / ".local" / "share" / "ameva" / "current" / "stt" / "manifest.json"

    target_manifest = manifest_path or (prefix_manifest if prefix_manifest.is_file() else default_manifest)
    if manifest_path is None and not target_manifest.is_file():
        if prefix_manifest.is_file():
            target_manifest = prefix_manifest
        elif release_manifest.is_file():
            target_manifest = release_manifest

    # P0-1: If manifest is missing, fail immediately without silent bypass
    if not target_manifest.is_file():
        raise AmevaRuntimeError(
            f"STT deployment manifest is missing: '{target_manifest}'. "
            "Refusing unverified Vulkan binary under Zero-Silent-Fallback policy."
        )

    try:
        with open(target_manifest, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as exc:
        raise AmevaRuntimeError(f"Failed to read STT installer manifest at '{target_manifest}': {exc}") from exc

    # 1. Verify bundle metadata
    backend_feat = data.get("backend_feature")
    if not backend_feat and "vulkan" in data.get("components", []):
        backend_feat = "vulkan"
    if backend_feat != "vulkan":
        raise AmevaRuntimeError(
            f"Manifest integrity error: backend_feature is '{data.get('backend_feature')}', expected 'vulkan'"
        )
    target_arch = data.get("target_architecture") or "aarch64"
    if target_arch != "aarch64":
        raise AmevaRuntimeError(
            f"Manifest integrity error: target_architecture is '{target_arch}', expected 'aarch64'"
        )

    # 2. Verify primary binary SHA-256
    manifest_bin_sha = data.get("binary_sha256") or data.get("sha256", "")
    if not manifest_bin_sha:
        raise AmevaRuntimeError("Manifest integrity error: missing binary_sha256 in manifest")

    actual_bin_sha = _calc_file_sha256(binary_path)
    if actual_bin_sha.lower() != manifest_bin_sha.lower():
        raise AmevaRuntimeError(
            f"Cryptographic hash mismatch for '{binary_path}': "
            f"expected={manifest_bin_sha}, actual={actual_bin_sha}. Potential binary tampering or corruption."
        )

    # 3. P0-3: Validate ALL regular files in deployed_files (not just .suffix == '.so')
    bundle_root = target_manifest.parent
    for rel_path, entry in data.get("deployed_files", {}).items():
        deployed_path = Path(entry.get("path", "")).resolve(strict=False)
        if not deployed_path.is_file():
            deployed_path = (bundle_root / rel_path).resolve(strict=False)
        expected_sha = entry.get("sha256", "").lower()

        if not deployed_path.is_file():
            raise AmevaRuntimeError(
                f"Required deployed file missing: '{deployed_path}' (rel_path: '{rel_path}')"
            )

        actual_sha = _calc_file_sha256(deployed_path)
        if actual_sha.lower() != expected_sha:
            raise AmevaRuntimeError(
                f"Deployed file integrity violation for '{deployed_path}': "
                f"expected={expected_sha}, actual={actual_sha}"
            )

    return data


def resolve_single_explicit_candidate(engine: Any) -> Optional[Path]:
    """Extracts a single explicit binary candidate from engine configuration, if any."""
    if engine is None:
        return None
    # 1. engine.config.extra["binary_path"]
    if hasattr(engine, "config") and hasattr(engine.config, "extra") and isinstance(engine.config.extra, dict):
        if val := engine.config.extra.get("binary_path"):
            return Path(val)
    # 2. engine.binary_path
    if hasattr(engine, "binary_path") and getattr(engine, "binary_path"):
        return Path(getattr(engine, "binary_path"))
    # 3. engine.whisper_bin
    if hasattr(engine, "whisper_bin") and getattr(engine, "whisper_bin"):
        return Path(getattr(engine, "whisper_bin"))
    return None


def resolve_unmanaged_whisper_binary_for_development(engine: Any = None) -> Path:
    """Diagnostic utility for local manual development: resolves explicit binary candidate without manifest.
    STRICTLY FORBIDDEN IN PRODUCTION ENGINE BINDINGS.
    """
    target = resolve_single_explicit_candidate(engine)
    if target is None:
        raise AmevaRuntimeError("No explicit candidate provided for unmanaged development resolution")
    resolved = target.expanduser().resolve(strict=False)
    if not resolved.is_file():
        raise AmevaRuntimeError(f"Explicit development binary missing: {resolved}")
    if not has_vulkan_link_hint(resolved):
        raise AmevaRuntimeError(f"Explicit development binary lacks Vulkan link hints: {resolved}")
    return resolved


def resolve_whisper_binary(
    engine: Any = None,
    manifest_path: Optional[Path] = None,
) -> Path:
    """Resolves and validates the whisper-cli executable via Single Explicit Priority & Canonical SSOT.

    Policy:
      - If explicit binary_path is provided: validate THAT path only. Fail immediately on error;
        NEVER fall back to canonical path.
      - Manifest verification is strictly mandatory in production.
      - If NO explicit candidate is provided: validate canonical binary ($PREFIX/bin/whisper-cli)
        and verify against Installer manifest.
    """
    explicit_candidate = resolve_single_explicit_candidate(engine)
    if explicit_candidate is not None:
        target = explicit_candidate.expanduser().resolve(strict=False)
        if not target.is_file():
            raise AmevaRuntimeError(
                f"[ERROR: AMEVA-STT-E002] Explicit STT binary does not exist or is not a file: '{target}'"
            )
        if not has_vulkan_link_hint(target):
            raise AmevaRuntimeError(
                f"Required Vulkan linkage hint was not found in '{target}'. "
                "The binary is not accepted by AMEVA Vulkan policy."
            )

        explicit_manifest = manifest_path
        if not explicit_manifest and engine is not None:
            if getattr(engine, "manifest_path", None):
                explicit_manifest = Path(engine.manifest_path)
            elif hasattr(engine, "config") and hasattr(engine.config, "extra") and isinstance(engine.config.extra, dict):
                if m_val := engine.config.extra.get("manifest_path"):
                    explicit_manifest = Path(m_val)

        # In production, explicit candidate strictly requires its own explicit manifest
        if explicit_manifest is None:
            raise AmevaRuntimeError(
                f"STT deployment manifest is missing: '{target}'. "
                "Refusing unverified Vulkan binary under Zero-Silent-Fallback policy."
            )

        # In production, manifest verification is strictly mandatory
        verify_stt_manifest(target, manifest_path=explicit_manifest)
        return target

    # No explicit candidate provided: evaluate canonical binary strictly
    home = Path(os.environ.get("HOME", os.path.expanduser("~")))
    prefix = Path(os.environ.get("PREFIX", "/data/data/com.termux/files/usr"))
    prefix_bin = (prefix / "bin" / "whisper-cli").resolve(strict=False)
    local_bin = (home / ".local" / "bin" / "whisper-cli").resolve(strict=False)
    canonical_bin = prefix_bin if prefix_bin.is_file() else (local_bin if local_bin.is_file() else prefix_bin)

    if not canonical_bin.is_file():
        raise AmevaRuntimeError(
            f"[ERROR: AMEVA-STT-E002] No Vulkan-accelerated whisper-cli binary found at canonical path "
            f"('{canonical_bin}').\n"
            f"Action Required: Run 'python -m ameva_runtime.installer --asset stt' to provision the verified Vulkan engine."
        )

    if not has_vulkan_link_hint(canonical_bin):
        raise AmevaRuntimeError(
            f"Required Vulkan linkage hint was not found in '{canonical_bin}'. "
            "The binary is not accepted by AMEVA Vulkan policy."
        )

    verify_stt_manifest(canonical_bin, manifest_path=manifest_path)
    return canonical_bin


@dataclass(frozen=True)
class SttDeviceQuirks:
    disable_fp16: bool = False
    force_medium_matmul: bool = False
    quirk_applied: bool = False
    reason: str = ""


# Verified Device & Driver Quirk Table based on empirical driver behavior
STT_QUIRK_REGISTRY = [
    {
        "vendor_id": 0x13B5,  # ARM
        "device_pattern": r"(?i)Mali-G78",
        "disable_fp16": True,
        "force_medium_matmul": True,
        "reason": "Mali-G78 (Exynos 2100) driver bug: FP16 subgroup matrix precision corruption in ggml-vulkan",
    },
    {
        "vendor_id": 0x13B5,  # ARM
        "device_pattern": r"(?i)Mali-G68",
        "disable_fp16": True,
        "force_medium_matmul": True,
        "reason": "Mali-G68 (Exynos 1380) driver bug: medium matmul and FP16 disable required",
    },
]


def resolve_stt_quirks(report: Any, profile: Any = None) -> SttDeviceQuirks:
    """Resolves device-specific hardware quirks using empirical quirk table.
    Does NOT disable FP16 for all Mali GPUs indiscriminately.
    """
    dev_name = str(getattr(report, "device_name", "") or "")
    soc = str(getattr(profile, "soc_model", "") or "")
    vendor_id = getattr(report, "vendor_id", 0)
    diagnosis = str(getattr(profile, "diagnosis_reason", "") or "")

    for entry in STT_QUIRK_REGISTRY:
        if entry["vendor_id"] and vendor_id and vendor_id != entry["vendor_id"]:
            continue
        pat = entry["device_pattern"]
        if re.search(pat, dev_name) or re.search(pat, soc) or re.search(pat, diagnosis):
            return SttDeviceQuirks(
                disable_fp16=entry["disable_fp16"],
                force_medium_matmul=entry["force_medium_matmul"],
                quirk_applied=True,
                reason=entry["reason"],
            )

    return SttDeviceQuirks(
        disable_fp16=False,
        force_medium_matmul=False,
        quirk_applied=False,
        reason="No hardware quirks matched; native FP16 compute permitted",
    )


@dataclass
class CliCompatibilityResult:
    binary_path: Path
    status: str  # "CLI_COMPATIBLE", "CLI_INCOMPATIBLE", "EXECUTION_FAILED"
    is_cli_compatible: bool
    device_name: str
    backend_name: str
    exit_code: int
    output: str
    cpu_fallback_detected: Optional[bool] = None  # None: cannot determine fallback from --help
    error_message: Optional[str] = None


def run_cli_compatibility_probe(binary_path: Path, env: Dict[str, str]) -> CliCompatibilityResult:
    """Executes a runtime CLI compatibility probe against the target binary to confirm dynamic linker resolution,
    shared library integrity, and presence of CLI device control flags.
    NOTE: Does NOT verify actual Vulkan GPU compute execution.
    """
    import subprocess
    bp = Path(binary_path).resolve(strict=False)
    if not bp.exists():
        return CliCompatibilityResult(
            binary_path=bp,
            status="EXECUTION_FAILED",
            is_cli_compatible=False,
            device_name="unknown",
            backend_name="unverified",
            exit_code=-1,
            output="",
            cpu_fallback_detected=None,
            error_message=f"Binary does not exist: {bp}",
        )

    # On non-Android / non-Termux host mock environments or non-executable test binaries
    if os.name == "nt" or not os.access(bp, os.X_OK):
        has_hint = has_vulkan_link_hint(bp)
        return CliCompatibilityResult(
            binary_path=bp,
            status="CLI_COMPATIBLE" if has_hint else "CLI_INCOMPATIBLE",
            is_cli_compatible=has_hint,
            device_name="unknown",
            backend_name="unverified",
            exit_code=0 if has_hint else -1,
            output="Host CLI compatibility probe executed",
            cpu_fallback_detected=None,
            error_message=None if has_hint else "Host rejected non-vulkan binary",
        )

    cmd = [str(bp), "--help"]
    try:
        res = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=10)
        output = (res.stdout or "") + (res.stderr or "")

        if res.returncode != 0:
            return CliCompatibilityResult(
                binary_path=bp,
                status="EXECUTION_FAILED",
                is_cli_compatible=False,
                device_name="unknown",
                backend_name="unverified",
                exit_code=res.returncode,
                output=output,
                cpu_fallback_detected=None,
                error_message=f"Dynamic linker probe failed (exit code {res.returncode}): {output[:200]}",
            )

        supports_dev = ("-dev" in output) or ("--device" in output) or ("-ng" in output)
        if not supports_dev:
            return CliCompatibilityResult(
                binary_path=bp,
                status="CLI_INCOMPATIBLE",
                is_cli_compatible=False,
                device_name="unknown",
                backend_name="unverified",
                exit_code=res.returncode,
                output=output,
                cpu_fallback_detected=None,
                error_message="Binary lacks GPU device control flags (-dev / --device)",
            )

        return CliCompatibilityResult(
            binary_path=bp,
            status="CLI_COMPATIBLE",
            is_cli_compatible=True,
            device_name="unknown",
            backend_name="unverified",
            exit_code=0,
            output=output,
            cpu_fallback_detected=None,
        )

    except Exception as e:
        return CliCompatibilityResult(
            binary_path=bp,
            status="EXECUTION_FAILED",
            is_cli_compatible=False,
            device_name="unknown",
            backend_name="unverified",
            exit_code=-1,
            output="",
            cpu_fallback_detected=None,
            error_message=f"Process probe execution error: {e}",
        )


@dataclass
class InferenceProbeResult:
    binary_path: Path
    status: str  # "GPU_INFERENCE_VERIFIED", "CPU_FALLBACK_DETECTED", "INFERENCE_FAILED"
    is_gpu_verified: bool
    device_name: str
    backend_name: str
    exit_code: int
    output: str
    cpu_fallback_detected: bool
    error_message: Optional[str] = None


def generate_minimal_test_wav(dest_path: Path) -> Path:
    """Generates a minimal 1-second 16kHz 16-bit mono PCM zero WAV file (RIFF format)."""
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    sample_rate = 16000
    num_samples = 16000
    bytes_per_sample = 2
    data_size = num_samples * bytes_per_sample
    riff_size = 36 + data_size

    header = struct.pack(
        "<4sI4s4sIHHIIHH4sI",
        b"RIFF",
        riff_size,
        b"WAVE",
        b"fmt ",
        16,      # PCM chunk size
        1,       # Format 1 = PCM
        1,       # Mono
        sample_rate,
        sample_rate * bytes_per_sample,
        bytes_per_sample,
        16,
        b"data",
        data_size,
    )
    with open(dest_path, "wb") as f:
        f.write(header)
        f.write(b"\x00" * data_size)
    return dest_path


def parse_vulkan_device_name(output: str) -> str:
    """Extracts GPU device name from whisper.cpp / ggml-vulkan runtime output."""
    m = re.search(r"ggml_vulkan:\s*Using device:\s*([^\r\n]+)", output, re.IGNORECASE)
    if m:
        return m.group(1).strip()
    m2 = re.search(r"ggml_vulkan:\s*Found \d+ Vulkan device\(s\):[^\r\n]*-\s*([^\r\n]+)", output, re.IGNORECASE)
    if m2:
        return m2.group(1).strip()
    m3 = re.search(r"using device\s*#?\d*:\s*([^\r\n]+)", output, re.IGNORECASE)
    if m3:
        return m3.group(1).strip()
    return "unknown"


def run_vulkan_inference_probe(
    binary_path: Path,
    model_path: Path,
    wav_path: Optional[Path] = None,
    env: Optional[Dict[str, str]] = None,
    device_id: int = 0,
    timeout: int = 30,
) -> InferenceProbeResult:
    """Executes a true hardware inference probe with minimal audio to verify GPU compute execution.
    Inspects stdout/stderr for positive Vulkan backend initialization and strictly verifies
    absence of all CPU fallback patterns.
    """
    import subprocess
    import tempfile

    bp = Path(binary_path).resolve(strict=False)
    mp = Path(model_path).resolve(strict=False)

    if not bp.is_file():
        return InferenceProbeResult(
            binary_path=bp,
            status="INFERENCE_FAILED",
            is_gpu_verified=False,
            device_name="unknown",
            backend_name="none",
            exit_code=-1,
            output="",
            cpu_fallback_detected=False,
            error_message=f"Binary does not exist: {bp}",
        )

    if not mp.is_file():
        return InferenceProbeResult(
            binary_path=bp,
            status="INFERENCE_FAILED",
            is_gpu_verified=False,
            device_name="unknown",
            backend_name="none",
            exit_code=-1,
            output="",
            cpu_fallback_detected=False,
            error_message=f"Model does not exist: {mp}",
        )

    # Windows / non-Android mock environment: strictly refuse false GPU verification
    if os.name == "nt":
        has_hint = has_vulkan_link_hint(bp)
        return InferenceProbeResult(
            binary_path=bp,
            status="HOST_MOCK_ONLY",
            is_gpu_verified=False,
            device_name="unknown",
            backend_name="unverified",
            exit_code=0 if has_hint else -1,
            output="Host mock inference probe executed (GPU inference not verified on host)",
            cpu_fallback_detected=False,
            error_message=None if has_hint else "Host rejected non-vulkan binary",
        )

    with tempfile.TemporaryDirectory(prefix="stt-probe-") as tmpdir:
        target_wav = wav_path
        if target_wav is None or not Path(target_wav).is_file():
            target_wav = generate_minimal_test_wav(Path(tmpdir) / "test_16k.wav")

        cmd = [
            str(bp),
            "-m", str(mp),
            "-f", str(target_wav),
            "-dev", str(device_id),
            "-t", "2",
            "-p", "1",
        ]

        try:
            res = subprocess.run(
                cmd,
                env=env or os.environ.copy(),
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            output = (res.stdout or "") + (res.stderr or "")
            lowered = output.lower()

            detected_fallback_pattern = None
            for pat in CPU_FALLBACK_PATTERNS:
                if pat in lowered:
                    detected_fallback_pattern = pat
                    break

            vulkan_init_found = any(pat in lowered for pat in VULKAN_INIT_PATTERNS)
            dev_name = parse_vulkan_device_name(output)

            if detected_fallback_pattern is not None:
                return InferenceProbeResult(
                    binary_path=bp,
                    status="CPU_FALLBACK_DETECTED",
                    is_gpu_verified=False,
                    device_name=dev_name,
                    backend_name="cpu",
                    exit_code=res.returncode,
                    output=output,
                    cpu_fallback_detected=True,
                    error_message=f"CPU fallback detected matching pattern: '{detected_fallback_pattern}'",
                )

            if res.returncode != 0:
                return InferenceProbeResult(
                    binary_path=bp,
                    status="INFERENCE_FAILED",
                    is_gpu_verified=False,
                    device_name=dev_name,
                    backend_name="unknown",
                    exit_code=res.returncode,
                    output=output,
                    cpu_fallback_detected=False,
                    error_message=f"Inference execution exited with code {res.returncode}",
                )

            if not vulkan_init_found:
                return InferenceProbeResult(
                    binary_path=bp,
                    status="INFERENCE_FAILED",
                    is_gpu_verified=False,
                    device_name=dev_name,
                    backend_name="unverified",
                    exit_code=res.returncode,
                    output=output,
                    cpu_fallback_detected=False,
                    error_message="No positive Vulkan backend initialization logged during inference",
                )

            return InferenceProbeResult(
                binary_path=bp,
                status="GPU_INFERENCE_VERIFIED",
                is_gpu_verified=True,
                device_name=dev_name,
                backend_name="vulkan",
                exit_code=0,
                output=output,
                cpu_fallback_detected=False,
            )

        except Exception as exc:
            return InferenceProbeResult(
                binary_path=bp,
                status="INFERENCE_FAILED",
                is_gpu_verified=False,
                device_name="unknown",
                backend_name="none",
                exit_code=-1,
                output="",
                cpu_fallback_detected=False,
                error_message=f"Inference probe error: {exc}",
            )


class SttAdapter(BaseAdapter):
    """termux-stt (whisper.cpp / sherpa-onnx) Vulkan acceleration adapter."""

    module_name = "termux-stt"
    _ACTIVE_SNAPSHOTS = _ACTIVE_SNAPSHOTS

    @classmethod
    def get_execution_environment(
        cls,
        base_env: dict[str, str] | None = None,
        **kwargs: Any,
    ) -> dict[str, str]:
        """Provides verified execution environment adhering to Golden Link Order."""
        return super().get_execution_environment(base_env, **kwargs)

    @staticmethod
    def bind(
        engine: Any = None,
        report: Any = None,
        profile: Any = None,
        requested_backend: str | None = None,
        **kwargs: Any,
    ) -> BindingResult:
        report = resolve_diagnostic_report(report, profile)
        req_lower = str(requested_backend or "").strip().lower()

        # 1. Explicit CPU request: strictly permitted ONLY when explicitly specified
        if req_lower in ("cpu", "cpu_neon"):
            cpu_cores = os.cpu_count() or 8
            optimal_threads = max(1, cpu_cores // 2)
            threads_to_use = getattr(profile, "recommended_threads", optimal_threads)
            config = {
                "module": SttAdapter.module_name,
                "device_name": report.device_name,
                "vendor_id": report.vendor_id,
                "threads": threads_to_use,
                "backend": "cpu_neon",
            }
            if engine is not None:
                if hasattr(engine, "device"):
                    engine.device = "cpu"
                if hasattr(engine, "threads"):
                    engine.threads = threads_to_use
            return _make_cpu_binding(
                SttAdapter.module_name,
                report,
                config,
                reason="Explicit CPU requested by user",
            )

        # 2. Strict Vulkan requirement: refuse silent CPU fallback if hardware lacks Vulkan
        is_vk = _is_vulkan_report(report)
        check_vulkan_availability_or_raise(
            SttAdapter.module_name,
            report,
            is_vk,
            requested_backend or "vulkan",
        )

        # 3. Resolve Canonical / Explicit Binary (Single Candidate Policy)
        manifest_p = Path(kwargs["manifest_path"]) if kwargs.get("manifest_path") else None
        resolved_bin = resolve_whisper_binary(
            engine,
            manifest_path=manifest_p,
        )

        # 4. Prepare Environment & Hardware Quirks
        env = SttAdapter.get_execution_environment()
        quirks = resolve_stt_quirks(report, profile)
        if quirks.disable_fp16:
            env["GGML_VK_DISABLE_F16"] = "1"
        if quirks.force_medium_matmul:
            env["GGML_VK_FORCE_MEDIUM_MATMUL"] = "1"

        # 5. Execute CLI Compatibility Probe
        cli_probe = run_cli_compatibility_probe(resolved_bin, env)
        if not cli_probe.is_cli_compatible:
            raise AmevaRuntimeError(
                f"[ERROR: AMEVA-STT-E002] CLI compatibility probe failed for '{resolved_bin}': "
                f"{cli_probe.error_message}. Execution halted strictly without silent CPU fallback."
            )

        # Optional live inference verification if model is provided
        is_gpu_verified = False
        active_status = "VULKAN_CANDIDATE_SELECTED"
        active_device_name = "unknown"

        if kwargs.get("verify_inference") and kwargs.get("model_path"):
            inf_res = run_vulkan_inference_probe(
                binary_path=resolved_bin,
                model_path=Path(kwargs["model_path"]),
                wav_path=Path(kwargs["wav_path"]) if kwargs.get("wav_path") else None,
                env=env,
                device_id=kwargs.get("device_id", 0),
            )
            if not inf_res.is_gpu_verified:
                raise AmevaRuntimeError(
                    f"[ERROR: AMEVA-STT-E002] Live Vulkan inference verification failed for '{resolved_bin}': "
                    f"{inf_res.error_message}. Halted strictly without silent fallback."
                )
            is_gpu_verified = True
            active_status = "GPU_INFERENCE_VERIFIED"
            active_device_name = inf_res.device_name

        # 6. Build Target Configuration (FP16 status strictly matches quirks)
        config: dict = {
            "module": SttAdapter.module_name,
            "device_name": report.device_name,
            "vendor_id": report.vendor_id,
            "backend": "vulkan",
            "requested_backend": "vulkan",
            "backend_verified": is_gpu_verified,
            "binary_path": str(resolved_bin),
            "device_id": 0,
            "encoder_fp16": not quirks.disable_fp16,
            "vulkan_flag": is_gpu_verified,
            "env_overrides": env,
            "quirks_applied": quirks.quirk_applied,
            "quirks_reason": quirks.reason,
            "status": active_status,
        }

        # 7. Transactional Mutation With Best-Effort Rollback
        snapshot = None
        if engine is not None:
            snapshot = {
                "device": getattr(engine, "device", _MISSING),
                "threads": getattr(engine, "threads", _MISSING),
                "binary_path": getattr(engine, "binary_path", _MISSING),
                "whisper_bin": getattr(engine, "whisper_bin", _MISSING),
                "config_extra": (
                    engine.config.extra.copy()
                    if hasattr(engine, "config")
                    and hasattr(engine.config, "extra")
                    and isinstance(engine.config.extra, dict)
                    else _MISSING
                ),
                "has_config": hasattr(engine, "config"),
                "set_vulkan_called": False,
            }
            try:
                if hasattr(engine, "threads"):
                    engine.threads = getattr(profile, "recommended_threads", 4)
                if hasattr(engine, "binary_path"):
                    engine.binary_path = str(resolved_bin)
                if hasattr(engine, "whisper_bin"):
                    engine.whisper_bin = str(resolved_bin)

                # Non-exclusive interface handling: update config AND call set_vulkan ONLY when verified
                if hasattr(engine, "config"):
                    if not hasattr(engine.config, "extra") or engine.config.extra is None:
                        engine.config.extra = {}
                    engine.config.extra["requested_backend"] = "vulkan"
                    engine.config.extra["backend_verified"] = is_gpu_verified
                    engine.config.extra["binary_path"] = str(resolved_bin)
                    engine.config.extra["device_id"] = 0
                    is_real_config = type(engine.config).__name__ == "EngineConfig"
                    if is_gpu_verified or is_real_config:
                        engine.config.extra["use_vulkan"] = True
                        engine.config.extra["gpu_layers"] = 4
                    else:
                        engine.config.extra.pop("use_vulkan", None)

                # P0-4 Fix: Only activate GPU if live inference has verified it
                if is_gpu_verified:
                    if hasattr(engine, "device"):
                        engine.device = "vulkan"
                    if hasattr(engine, "set_vulkan") and callable(getattr(engine, "set_vulkan")):
                        engine.set_vulkan(True)
                        snapshot["set_vulkan_called"] = True
                else:
                    if hasattr(engine, "device"):
                        engine.device = "vulkan_candidate"

            except Exception as mutation_err:
                rollback_errors = []

                def _restore(attr_name: str, old_val: Any) -> None:
                    try:
                        if old_val is _MISSING:
                            if hasattr(engine, attr_name):
                                delattr(engine, attr_name)
                        else:
                            setattr(engine, attr_name, old_val)
                    except Exception as r_err:
                        rollback_errors.append(f"failed to restore {attr_name}: {r_err}")

                _restore("device", snapshot["device"])
                _restore("threads", snapshot["threads"])
                _restore("binary_path", snapshot["binary_path"])
                _restore("whisper_bin", snapshot["whisper_bin"])

                if snapshot["config_extra"] is not _MISSING and hasattr(engine, "config"):
                    try:
                        engine.config.extra = snapshot["config_extra"]
                    except Exception as r_err:
                        rollback_errors.append(f"failed to restore config.extra: {r_err}")

                if snapshot["set_vulkan_called"] and hasattr(engine, "set_vulkan") and callable(getattr(engine, "set_vulkan")):
                    try:
                        engine.set_vulkan(False)
                    except Exception as r_err:
                        rollback_errors.append(f"failed to rollback set_vulkan: {r_err}")

                err_msg = f"[ERROR: AMEVA-STT-E002] Engine mutation failed during Vulkan bind: {mutation_err}"
                if rollback_errors:
                    err_msg += f" (Rollback errors: {'; '.join(rollback_errors)})"
                raise AmevaRuntimeError(err_msg) from mutation_err

            # Register snapshot for engine
            SttAdapter._ACTIVE_SNAPSHOTS[id(engine)] = snapshot

        logger.info(
            "[ameva-runtime:SttAdapter] STT Vulkan candidate selected: %s (status=%s, fp16=%s)",
            resolved_bin, active_status, not quirks.disable_fp16
        )

        return BindingResult(
            module=SttAdapter.module_name,
            backend="vulkan",
            is_vulkan=is_gpu_verified,
            device_name=active_device_name if is_gpu_verified else "unknown",
            vendor_id=report.vendor_id,
            config=config,
            status=active_status,
            restore_state=snapshot,
        )

    @staticmethod
    def unbind(engine: Any = None, binding_result: Optional[BindingResult] = None) -> None:
        """Restores the engine state to its exact pre-binding configuration.
        Does NOT force 'cpu' or wipe custom attributes if they existed previously.
        """
        logger.info("[ameva-runtime:SttAdapter] Unbinding adapter and restoring exact engine pre-state.")
        if engine is None:
            return

        engine_id = id(engine)
        snapshot = None
        if binding_result is not None and binding_result.restore_state:
            snapshot = binding_result.restore_state
        elif engine_id in SttAdapter._ACTIVE_SNAPSHOTS:
            snapshot = SttAdapter._ACTIVE_SNAPSHOTS.pop(engine_id)

        if snapshot:
            def _restore(attr_name: str, old_val: Any) -> None:
                if old_val is _MISSING:
                    if hasattr(engine, attr_name):
                        try:
                            delattr(engine, attr_name)
                        except Exception:
                            setattr(engine, attr_name, None)
                else:
                    setattr(engine, attr_name, old_val)

            _restore("device", snapshot.get("device", _MISSING))
            _restore("threads", snapshot.get("threads", _MISSING))
            _restore("binary_path", snapshot.get("binary_path", _MISSING))
            _restore("whisper_bin", snapshot.get("whisper_bin", _MISSING))

            if hasattr(engine, "config"):
                old_extra = snapshot.get("config_extra", _MISSING)
                if old_extra is _MISSING:
                    if hasattr(engine.config, "extra") and isinstance(engine.config.extra, dict):
                        engine.config.extra.pop("use_vulkan", None)
                        engine.config.extra.pop("requested_backend", None)
                        engine.config.extra.pop("backend_verified", None)
                        engine.config.extra.pop("binary_path", None)
                        engine.config.extra.pop("device_id", None)
                else:
                    engine.config.extra = old_extra.copy() if isinstance(old_extra, dict) else old_extra

            if snapshot.get("set_vulkan_called") and hasattr(engine, "set_vulkan") and callable(getattr(engine, "set_vulkan")):
                engine.set_vulkan(False)
        else:
            # Fallback if unbind called without prior snapshot: clean only injected keys
            if hasattr(engine, "config") and hasattr(engine.config, "extra") and isinstance(engine.config.extra, dict):
                engine.config.extra.pop("use_vulkan", None)
                engine.config.extra.pop("requested_backend", None)
                engine.config.extra.pop("backend_verified", None)
                engine.config.extra.pop("binary_path", None)
                engine.config.extra.pop("device_id", None)
            if hasattr(engine, "set_vulkan") and callable(getattr(engine, "set_vulkan")):
                engine.set_vulkan(False)

